version: "3.9"

services:
  chess:
    build: .
    container_name: chess_container
    image: personal-chess-performance:latest
    volumes:
      - ./data-volume:/app/Data       # mount host Data folder into container
    ports:
      - "8888:8888"            # optional, for Jupyter notebooks
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root

volumes:
  data-volume: