version: "3.9"

services:
  chess-ml:
    build: .
    container_name: Personal-Chess-Performance
    volumes:
      - ./Data:/app/Data       # mount host Data folder into container
    ports:
      - "8888:8888"            # optional, for Jupyter notebooks
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root